// Generated by `stoneware build --target vercel`. Do not edit.
//
// Vercel's Bun framework preset detects the Bun.serve() call inside this import
// and routes requests through it. The port and hostname the bundle passes are
// ignored on Vercel and used only when this file is run locally.
import "./.stoneware/server.js";
